### ISSUE TITLE
hlsenc support

### ISSUE THREAD

**Issue by mkozjak** [imkira/go-libav#35]
Hi,

Is there a way to include hlsenc (a part of libavformat) to be able to encrypt HLS content?

**Comment by imkira** [comment]
What API specifically do you need?
As far as I can see you just need to set the appropriate options when creating the format/encoder context to be able to encrypt with HLS.
There is no way though to call HLS functions explicitly as they are private.

**Comment by mkozjak** [comment]
Yeah, they are private so I'm closing the ticket. Already found the solution for my problem, too.
